/* Sistemi Genit — Modul Paga, i frymëzuar nga rrjedha e Boshti Paga */
(function (global) {
  'use strict';
  var App = global.App;
  if (!App || global.__SG_PAYROLL_UI__) return;
  global.__SG_PAYROLL_UI__ = true;
  var KEY = 'sg_payroll_v1';
  var state = { employees: [], entries: [], settings: { pensionEmployee: 9.5, healthEmployee: 1.7, pensionEmployer: 15, healthEmployer: 1.7, pensionCap: 186416, taxBand1: 40000, taxBand2: 50000, taxRate1: 13, taxRate2: 23 } };
  function load() { try { var x = JSON.parse(localStorage.getItem(KEY) || '{}'); state = Object.assign(state, x); state.settings = Object.assign({ pensionEmployee: 9.5, healthEmployee: 1.7, pensionEmployer: 15, healthEmployer: 1.7, pensionCap: 186416, taxBand1: 40000, taxBand2: 50000, taxRate1: 13, taxRate2: 23 }, state.settings || {}); } catch (_) {} }
  function save() { localStorage.setItem(KEY, JSON.stringify(state)); }
  function esc(v) { return App.esc ? App.esc(v == null ? '' : String(v)) : String(v == null ? '' : v).replace(/[&<>\"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); }
  function n(v) { var x = Number(v); return Number.isFinite(x) ? x : 0; }
  function money(v) { return n(v).toLocaleString('sq-AL', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
  function month() { return App._sgPayrollMonth || new Date().toISOString().slice(0, 7); }
  function calc(e) {
    var s = state.settings, gross = n(e.base) + n(e.allowance) + n(e.overtimeHours) * n(e.overtimeRate) + n(e.bonus);
    var pensionE = Math.min(gross, n(s.pensionCap)) * n(s.pensionEmployee) / 100, healthE = gross * n(s.healthEmployee) / 100;
    var taxable = Math.max(0, gross - pensionE - healthE), tax = taxable <= n(s.taxBand1) ? 0 : taxable <= n(s.taxBand2) ? (taxable - n(s.taxBand1)) * n(s.taxRate1) / 100 : (n(s.taxBand2) - n(s.taxBand1)) * n(s.taxRate1) / 100 + (taxable - n(s.taxBand2)) * n(s.taxRate2) / 100;
    var pensionR = Math.min(gross, n(s.pensionCap)) * n(s.pensionEmployer) / 100, healthR = gross * n(s.healthEmployer) / 100;
    return { gross: gross, pensionE: pensionE, healthE: healthE, taxable: taxable, tax: tax, net: gross - pensionE - healthE - tax, pensionR: pensionR, healthR: healthR, employerCost: gross + pensionR + healthR };
  }
  function rows() { return state.entries.filter(function (x) { return x.month === month(); }).map(function (x) { return Object.assign({}, x, { employee: state.employees.find(function (e) { return e.id === x.employeeId; }) || { name: 'Punonjës i fshirë' } }); }); }
  function shell(title, body) { var c = document.getElementById('content'); if (c) c.innerHTML = '<div class="sg-payroll-head"><div><div class="sg-payroll-kicker">BURIME NJERËZORE · PAGAT</div><h2>' + title + '</h2><p>Lista mujore, llogaritje bruto–neto, kontribute dhe eksport për Excel.</p></div><div class="sg-payroll-period"><label>Periudha<input id="sg-pay-month" type="month" value="' + esc(month()) + '" onchange="App.sgPayrollSetMonth(this.value)"></label></div></div>' + body; }
  function menu() { var side = document.querySelector('.sidebar'); if (!side || document.getElementById('sg-payroll-nav')) return; var d = document.createElement('div'); d.id = 'sg-payroll-nav'; d.className = 'nav-section'; d.innerHTML = '<div class="nav-section-title">PAGA & BURIME NJERËZORE</div><div class="nav-item" data-sg-payroll="list"><span class="icon">💶</span><span>Lista e Pagave</span></div><div class="nav-item" data-sg-payroll="employees"><span class="icon">👥</span><span>Punonjësit</span></div><div class="nav-item" data-sg-payroll="settings"><span class="icon">⚙️</span><span>Parametrat e Pagave</span></div>'; side.appendChild(d); d.querySelectorAll('[data-sg-payroll]').forEach(function (x) { x.onclick = function () { App.navigate('payroll_' + x.dataset.sgPayroll); }; }); }
  function nav(view, title) { App.currentView = view; document.querySelectorAll('.nav-item').forEach(function (x) { x.classList.toggle('active', x.dataset.sgPayroll === view.replace('payroll_', '')); }); }
  App.sgPayrollSetMonth = function (v) { App._sgPayrollMonth = v || month(); App.viewPayrollList(); };
  App.navigate = (function (base) { return function (view) { if (view === 'payroll_list') { nav(view); return App.viewPayrollList(); } if (view === 'payroll_employees') { nav(view); return App.viewPayrollEmployees(); } if (view === 'payroll_settings') { nav(view); return App.viewPayrollSettings(); } return base.apply(this, arguments); }; })(App.navigate);
  App.viewPayrollList = function () { load(); var rr = rows(), totals = rr.reduce(function (a, x) { var c = calc(x); Object.keys(c).forEach(function (k) { a[k] = (a[k] || 0) + c[k]; }); return a; }, {}); var body = '<div class="sg-payroll-actions"><button class="btn btn-primary" onclick="App.sgPayrollAddEntry()">+ Shto në listë</button><button class="btn btn-outline" onclick="App.sgPayrollExport()">⬇ Eksporto Excel</button><button class="btn btn-outline" onclick="App.sgPayrollPrint()">Printo listën</button></div><div class="sg-payroll-kpis"><div><span>Punonjës</span><strong>' + rr.length + '</strong></div><div><span>Bruto</span><strong>' + money(totals.gross) + ' ALL</strong></div><div><span>TAP</span><strong>' + money(totals.tax) + ' ALL</strong></div><div><span>Neto për pagesë</span><strong>' + money(totals.net) + ' ALL</strong></div><div><span>Kosto punëdhënësi</span><strong>' + money(totals.employerCost) + ' ALL</strong></div></div><div class="card"><div class="card-title"><span>Lista e Pagave — ' + esc(month()) + '</span><div><button class="btn btn-outline btn-sm" onclick="App.viewPayrollEmployees()">Menaxho punonjësit</button></div></div><div class="report-table-wrap"><table><thead><tr><th>Punonjësi</th><th>Pozicioni</th><th>Ditë</th><th>Bruto</th><th>SS punonjës</th><th>SH punonjës</th><th>TAP</th><th>Neto</th><th>Kosto totale</th><th></th></tr></thead><tbody>' + (rr.length ? rr.map(function (x) { var c = calc(x); return '<tr><td><strong>' + esc(x.employee.name) + '</strong><br><small>' + esc(x.employee.personalId || '') + '</small></td><td>' + esc(x.employee.position || '') + '</td><td>' + esc(x.days || 0) + '</td><td class="text-right">' + money(c.gross) + '</td><td class="text-right">' + money(c.pensionE) + '</td><td class="text-right">' + money(c.healthE) + '</td><td class="text-right">' + money(c.tax) + '</td><td class="text-right"><strong>' + money(c.net) + '</strong></td><td class="text-right">' + money(c.employerCost) + '</td><td><button class="btn btn-outline btn-sm" onclick="App.sgPayrollEditEntry(\'' + x.id + '\')">Edito</button></td></tr>'; }).join('') : '<tr><td colspan="10" class="sg-payroll-empty">Nuk ka regjistrime për këtë muaj. Shto punonjësit në listë për të filluar.</td></tr>') + '</tbody></table></div></div><div class="sg-payroll-note">Parametrat janë të ndryshueshëm te “Parametrat e Pagave”. Kontrollo normat dhe kufijtë sipas legjislacionit në fuqi para deklarimit zyrtar.</div>'; shell('Lista e Pagave', body); };
  function employeeForm(e) { e = e || {}; return '<div class="sg-payroll-form"><label>Emri i plotë<input id="sg-pe-name" value="' + esc(e.name || '') + '" required></label><label>Nr. personal / NIPT<input id="sg-pe-id" value="' + esc(e.personalId || '') + '"></label><label>Pozicioni<input id="sg-pe-position" value="' + esc(e.position || '') + '"></label><label>IBAN<input id="sg-pe-iban" value="' + esc(e.iban || '') + '"></label><div class="sg-payroll-form-actions"><button class="btn btn-primary" onclick="App.sgPayrollSaveEmployee(\'' + (e.id || '') + '\')">Ruaj punonjësin</button></div></div>'; }
  App.viewPayrollEmployees = function () { load(); var body = '<div class="sg-payroll-actions"><button class="btn btn-primary" onclick="App.sgPayrollNewEmployee()">+ Punonjës i ri</button><button class="btn btn-outline" onclick="App.viewPayrollList()">← Lista e pagave</button></div><div class="card"><div class="card-title"><span>Regjistri i Punonjësve</span></div><div class="report-table-wrap"><table><thead><tr><th>Emri</th><th>Nr. personal</th><th>Pozicioni</th><th>IBAN</th><th></th></tr></thead><tbody>' + (state.employees.length ? state.employees.map(function (e) { return '<tr><td><strong>' + esc(e.name) + '</strong></td><td>' + esc(e.personalId || '') + '</td><td>' + esc(e.position || '') + '</td><td>' + esc(e.iban || '') + '</td><td><button class="btn btn-outline btn-sm" onclick="App.sgPayrollEditEmployee(\'' + e.id + '\')">Edito</button></td></tr>'; }).join('') : '<tr><td colspan="5" class="sg-payroll-empty">Nuk ka punonjës të regjistruar.</td></tr>') + '</tbody></table></div></div>'; shell('Punonjësit', body); };
  App.sgPayrollNewEmployee = function () { var name = prompt('Emri i plotë i punonjësit:'); if (!name) return; state.employees.push({ id: 'e_' + Date.now(), name: name }); save(); App.viewPayrollEmployees(); };
  App.sgPayrollEditEmployee = function (id) { var e = state.employees.find(function (x) { return x.id === id; }); if (!e) return; var name = prompt('Emri i punonjësit:', e.name); if (name) e.name = name; e.position = prompt('Pozicioni:', e.position || '') || e.position || ''; e.personalId = prompt('Nr. personal / NIPT:', e.personalId || '') || e.personalId || ''; e.iban = prompt('IBAN:', e.iban || '') || e.iban || ''; save(); App.viewPayrollEmployees(); };
  App.sgPayrollAddEntry = function (id) { load(); var existing = state.entries.find(function (z) { return z.id === id; }) || {}; var e = state.employees.find(function (z) { return z.id === existing.employeeId; }) || state.employees[0]; if (!e) { alert('Shto fillimisht një punonjës.'); return App.viewPayrollEmployees(); } var chosen = prompt('Zgjidh ID-në e punonjësit:\n' + state.employees.map(function (x) { return x.id + ' — ' + x.name; }).join('\n'), e.id); var emp = state.employees.find(function (x) { return x.id === chosen; }) || e; var base = prompt('Paga bazë bruto (ALL):', existing.base || '0'); var allowance = prompt('Shtesa (ALL):', existing.allowance || '0'); var overtimeHours = prompt('Orë shtesë:', existing.overtimeHours || '0'); var overtimeRate = prompt('Çmimi/orë shtesë (ALL):', existing.overtimeRate || '0'); var bonus = prompt('Shpërblim (ALL):', existing.bonus || '0'); var days = prompt('Ditë pune:', existing.days || '22'); state.entries = state.entries.filter(function (x) { return !(x.month === month() && x.employeeId === emp.id) && x.id !== id; }); state.entries.push({ id: id || 'p_' + Date.now(), month: month(), employeeId: emp.id, base: n(base), allowance: n(allowance), overtimeHours: n(overtimeHours), overtimeRate: n(overtimeRate), bonus: n(bonus), days: n(days) }); save(); App.viewPayrollList(); };
  App.sgPayrollEditEntry = function (id) { var x = state.entries.find(function (z) { return z.id === id; }); if (x) App.sgPayrollAddEntry(id); };
  App.viewPayrollSettings = function () { load(); var s = state.settings; var fields = [['pensionEmployee','SS punonjës %'],['healthEmployee','SH punonjës %'],['pensionEmployer','SS punëdhënës %'],['healthEmployer','SH punëdhënës %'],['pensionCap','Tavan kontributesh'],['taxBand1','Pragu i parë TAP'],['taxBand2','Pragu i dytë TAP'],['taxRate1','Norma TAP pragu 1 %'],['taxRate2','Norma TAP pragu 2 %']]; shell('Parametrat e Pagave', '<div class="card"><p class="sg-payroll-note">Konfiguro normat sipas vendit dhe vitit tatimor. Vlerat ruhen vetëm për këtë instalim.</p><div class="sg-payroll-form">' + fields.map(function (f) { return '<label>' + f[1] + '<input type="number" step="0.01" id="sg-ps-' + f[0] + '" value="' + esc(s[f[0]]) + '"></label>'; }).join('') + '<div class="sg-payroll-form-actions"><button class="btn btn-primary" onclick="App.sgPayrollSaveSettings()">Ruaj parametrat</button></div></div></div>'); };
  App.sgPayrollSaveSettings = function () { Object.keys(state.settings).forEach(function (k) { var x = document.getElementById('sg-ps-' + k); if (x) state.settings[k] = n(x.value); }); save(); alert('Parametrat u ruajtën.'); App.viewPayrollList(); };
  function exportRows() { return rows().map(function (x) { var c = calc(x); return [x.employee.name, x.employee.personalId || '', x.employee.position || '', x.days || 0, c.gross, c.pensionE, c.healthE, c.taxable, c.tax, c.net, c.pensionR, c.healthR, c.employerCost]; }); }
  App.sgPayrollExport = function () { var h = ['Punonjësi', 'Nr. personal', 'Pozicioni', 'Ditë', 'Bruto', 'SS punonjës', 'SH punonjës', 'Paga e tatueshme', 'TAP', 'Paga neto', 'SS punëdhënës', 'SH punëdhënës', 'Kosto totale']; var html = '<html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial}th,td{border:1px solid #bbb;padding:6px}th{background:#5b4a8a;color:white}td{mso-number-format:"0.00"}</style></head><body><h2>Lista e Pagave — ' + esc(month()) + '</h2><table><tr>' + h.map(function (x) { return '<th>' + esc(x) + '</th>'; }).join('') + '</tr>' + exportRows().map(function (r) { return '<tr>' + r.map(function (x) { return '<td>' + esc(typeof x === 'number' ? x.toFixed(2) : x) + '</td>'; }).join('') + '</tr>'; }).join('') + '</table></body></html>'; var a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([html], { type: 'application/vnd.ms-excel' })); a.download = 'Lista_Pagave_' + month() + '.xls'; a.click(); URL.revokeObjectURL(a.href); };
  App.sgPayrollPrint = function () { var w = global.open('', '_blank'); if (!w) return; w.document.write('<html><head><title>Lista e Pagave</title></head><body>' + document.querySelector('.card').outerHTML + '</body></html>'); w.document.close(); w.print(); };
  load(); menu(); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', menu); else setTimeout(menu, 0);
  global.SGPayroll = { state: state, calculate: calc, export: App.sgPayrollExport };
})(window);
/* SG_PAYROLL_UI_END */
