'use strict';
const assert=require('node:assert/strict');
const base=process.env.TEST_API_URL||'http://127.0.0.1:3000';
async function call(path,options={}){const headers=Object.assign({'Content-Type':'application/json'},options.headers||{});const response=await fetch(base+path,{method:options.method||'GET',headers,body:options.body===undefined?undefined:JSON.stringify(options.body)});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data=text;}if(!response.ok){const error=new Error((data&&data.message)||`HTTP ${response.status}`);error.status=response.status;error.data=data;throw error;}return data;}
(async()=>{
  const stamp=Date.now();
  const setup=await call('/api/setup/admin',{method:'POST',body:{organizationName:'Genit Test '+stamp,companyName:'Kompania Test',companyNipt:'L00000000T',warehouseName:'Magazina Qendrore',adminName:'Admin Test',username:'admin'+stamp,email:'admin'+stamp+'@example.com',password:'TestPass123!'}});
  assert.ok(setup.token);
  const auth={Authorization:'Bearer '+setup.token};
  const modules=await call('/api/modules',{headers:auth});
  const financeModule=modules.find(x=>x.group==='Arka & Banka');
  assert.equal(financeModule.active,true);
  assert.equal(financeModule.phase,5);
  const cash=await call('/api/finance/accounts',{method:'POST',headers:auth,body:{companyId:setup.companyId,warehouseId:setup.warehouseId,accountKind:'CASH',code:'ARKA-LEK',name:'Arka Kryesore',currency:'ALL',openingBalance:1000,openingDate:'2026-07-23',active:true,notes:'Test'}});
  const bank=await call('/api/finance/accounts',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountKind:'BANK',code:'BANKA-ALL',name:'Banka Kryesore',currency:'ALL',openingBalance:0,openingDate:'2026-07-23',bankName:'Banka Test',iban:'AL00000000000000000000000000',active:true,notes:'Test'}});
  const payment=await call('/api/finance/documents',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountId:cash.id,documentType:'CASH_PAYMENT',documentDate:'2026-07-23',currency:'ALL',amount:200,exchangeRate:1,description:'Pagesë test',referenceNo:'REF-PAY',allocations:[]}});
  assert.match(payment.document_no,/^MP-2026-/);
  await call('/api/finance/documents/'+payment.id+'/post',{method:'POST',headers:auth,body:{}});
  let accounts=await call('/api/finance/accounts',{headers:auth});
  assert.equal(Number(accounts.find(x=>x.id===cash.id).balance),800);
  const tooLarge=await call('/api/finance/documents',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountId:cash.id,documentType:'CASH_PAYMENT',documentDate:'2026-07-23',currency:'ALL',amount:900,exchangeRate:1,description:'Duhet bllokuar',referenceNo:'REF-BLOCK',allocations:[]}});
  let blocked=false;try{await call('/api/finance/documents/'+tooLarge.id+'/post',{method:'POST',headers:auth,body:{}});}catch(error){blocked=error.status===409;}assert.equal(blocked,true);
  const receipt=await call('/api/finance/documents',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountId:cash.id,documentType:'CASH_RECEIPT',documentDate:'2026-07-23',currency:'ALL',amount:500,exchangeRate:1,description:'Arkëtim test',referenceNo:'REF-REC',allocations:[]}});
  await call('/api/finance/documents/'+receipt.id+'/post',{method:'POST',headers:auth,body:{}});
  accounts=await call('/api/finance/accounts',{headers:auth});
  assert.equal(Number(accounts.find(x=>x.id===cash.id).balance),1300);
  const bankReceipt=await call('/api/finance/documents',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountId:bank.id,documentType:'BANK_RECEIPT',documentDate:'2026-07-23',valueDate:'2026-07-23',currency:'ALL',amount:750,exchangeRate:1,description:'Hyrje bankare',referenceNo:'EXT-001',allocations:[]}});
  await call('/api/finance/documents/'+bankReceipt.id+'/post',{method:'POST',headers:auth,body:{}});
  const reconciled=await call('/api/finance/documents/'+bankReceipt.id+'/reconcile',{method:'POST',headers:auth,body:{reconciled:true,reconciliationRef:'STATEMENT-001'}});
  assert.equal(reconciled.reconciled,true);
  const closing=await call('/api/finance/cash-closings',{method:'POST',headers:auth,body:{companyId:setup.companyId,accountId:cash.id,closingDate:'2026-07-23',physicalBalance:1300,denominations:[],notes:'Mbyllje test'}});
  assert.equal(Number(closing.difference),0);
  const overview=await call('/api/finance/reports/overview?from=2026-07-23&to=2026-07-23',{headers:auth});
  assert.equal(Number(overview.totals.cash_receipts),500);
  assert.equal(Number(overview.totals.cash_payments),200);
  assert.equal(Number(overview.totals.bank_receipts),750);
  assert.equal(Number(overview.unreconciled.count),0);
  console.log(JSON.stringify({ok:true,cashBalance:1300,bankBalance:750,blockedNegative:true,reconciled:true,closingDifference:0},null,2));
})().catch(error=>{console.error(error);if(error.data)console.error(error.data);process.exit(1);});
